### ISSUE TITLE
Zero-width space characters break JS code when copied

### ISSUE THREAD

**Issue by SimonSteinberger** [Blender3D/rainbow.linenumbers.js#3]
Great extension for rainbow. Makes it really stand out. Just one real problem: The zero-width space get copied to clipboard and result in an "Illegal character" error in JavaScript. Probably other languages are concerned by this, too.

So, it would be great to find a replacement or another solution. For the time, I've replaced the &#8203; with an empty string. Empty lines are removed when copied to clipboard, but that better than having a broken code.

**Comment by SimonSteinberger** [comment]
Works perfectly so far! Thanks :+1:

**Comment by Blender3D** [comment]
No problem. I haven't had the chance to test it in many older browsers, so let me know if you see any issues.

**Comment by SimonSteinberger** [comment]
It's working fine in current versions of Chrome, FF, and IE down to version 9. IE 8 has issues with line breaks in my case: Syntax highlighting works properly, but I can't get it to create any line breaks. So, all code appears in a single, long line :-) Well, IE 8 - people using it have well deserved a little punishment :8ball:
