### ISSUE TITLE
multi-line comments break with embedded languages

### ISSUE THREAD

**Issue by DhatesCode** [Blender3D/rainbow.linenumbers.js#6]
Hi

This addition to rainbow is great, but it's breaking multi-line comments with embedded languages.

If you use the latest version of rainbow with your script and the following code, you'll see what I mean. Typically the first line is seen as a comment. The rest just shows up as "line-code."

Example code you can try is below, and you can also check [this fiddle](https://jsfiddle.net/DhatesCode/7j2nfmbs/)

``` html
<pre><code data-language="html">&lt;script&gt;
/* J stuff */
jQuery(function ($) {
    $(".rump").click(function () {
        $(".underwear").toggleClass('soiled');
    });
});
&lt;/script&gt;

&lt;style&gt;
/*-------------------------------------
                  Style stuff
-------------------------------------*/
.foo { color: brown }
.bar { color: yellow }

/* blah */
.snow:before { background-color: #eee }
.snow:after { background-color: yellow }
&lt;/style&gt;

&lt;?php
/*
PHP Comment
*/
function test_function() { // blah
    if ( $x == $y ) {
        do('something');
    }
    else {
        do('something_else');
    }
}
?&gt;</code></pre>
```

**Comment by Zir0-93** [comment]
@DhatesCode  have you found any work around in the mean time?

**Comment by DhatesCode** [comment]
I haven't tried yet. I'm assuming something like the following CSS might work (targeting line numbers):

```css
.line-12 { color:#888 }
```
or maybe for specif `<pre>` tags you could give a class and then use `+` selectors or `>`
```css
pre.my-class .comment + .line-code, .my-class .line-13 { color:#888 }
```

Only problem with this is that it's not dynamic, so you'd have to do it manually so as not to mess up things if you have more than one `<pre>` on a page, or just use inline CSS so it's not in your main style sheet. I'd try and fix it but I don't know javascript at all.

**Comment by Blender3D** [comment]
I'll take a look at it, thanks for opening the issue.

**Comment by JohnEcks** [comment]
no problem. thanks for the cool script ;)

**Comment by DhatesCode** [comment]
Sorry was on my friend's machine and he was logged in :P  No worries and thanks for the script.
